#!/usr/bin/env node
const Path   = require('path')
const vm     = require('vm')
const fs     = require('fs')
const gulp   = require('gulp4')
const gutil  = require('gulp-util')
const util   = require('util')
const assert = require('assert')

function repr(val, depth, showHidden) {
  return util.inspect(val, {
    colors:true,
    depth: depth === undefined ? 2 : depth,
    maxArrayLength: 25,
    breakLength: 80,
    showHidden
  })
}

function commonPrefixLen(names, sep) {
  var i, pos, sc = sep.charCodeAt(0);
  for (pos = 0; ; pos++) {
    for (i = 0; i < names.length; i++) {
      let c = names[i].charCodeAt(pos)
      if (c && c == names[0].charCodeAt(pos)) {
        continue;
      }
      while (pos > 0 && names[0].charCodeAt(--pos) != sc) {}
      return pos;
    }
  }
  return 0;
}

function commonParentDir(paths) {
  const cplen = commonPrefixLen(paths.map(path => {
    let p = path.indexOf('*')
    return (p != -1) ? path.substr(0, p) : path
  }), '/')
  return (cplen == 0) ? '/' : paths[0].substr(0, cplen)
}

function isfile(filename) {
  try { return fs.statSync(filename).isFile() } catch (_) { return false }
}

function fmthrtime(t) { // t: [seconds, nanoseconds] => string
  let ms = (t[1] / 1000000).toFixed(0)
  if (ms == '0') { ms = '<1' }
  return t[0] <= 0 ? (ms + 'ms') :
         (t[0] + '.' + ms + 's') ;
}

function parseargs(inargs) {
  let optsEnded = false, m
  const opts = {__proto__:{
    forEach(f, ctx) {
      Object.keys(this).forEach(k => f.call(this, k, this[k]), ctx)
    },
    get(namePrefix, defaultValue) {
      for (let name of Object.keys(this)) {
        if (name.length >= namePrefix.length && name.indexOf(namePrefix) == 0) {
          return {name, value: this[name]};
        }
      }
      return {name: namePrefix, value: defaultValue}
    }
  }}
  const re = /^-{1,2}([^=:]+)(?:\s*[=:]\s*(.*)|)$/
  const args = []
  let argsEnded = false
  for (let i = 0, L = inargs.length; i != L; ++i) {
    let arg = inargs[i]
    if (arg == '--') {
      argsEnded = true
    } else if (!argsEnded && arg[0] == '-') {
      let m = re.exec(arg)
      opts[m[1]] = m[2] === undefined ? true : m[2]
    } else {
      args.push(arg)
    }
  }
  return {opts, args}
}

function checkArg(argname, value, type, progpath) {
  if (typeof value != type) {
    console.error(
      `Unexpected argument value ${JSON.stringify(value)} for -${argname}.` +
      ` Expected ${type}.`
    )
    usage(progpath)
  } else if (type == 'string') {
    value = value.trim()
    if (value.length == 0) {
      console.error(`Argument -${argname}=<string> requires a non-empty value.`)
      usage(progpath)
    }
  }
  return value
}

function parseBool(s) {
  if (typeof s == 'string') {
    s = s.toLowerCase()
    return s == 'true' || s == 'yes' || s == 'on' || !!parseFloat(s)
  }
  return !!s
}

function usage(progpath, askedForHelp) {
  const progname = Path.basename(progpath)
  const desc0 = [
    'Build TypeScript and JavaScript projects into distributable packages.',
  ], desc1 = [
`Usage: ${progpath} [options] [<srcpath>]
options:
  -h[elp]               Show description and detailed help for this program.
  -o[output]=<outfile>  Filename prefix for output(s). E.g. 'a/b' => 'a/b.js'.
                        If not provided, "<srcpath>/<pkgname>" is used when
                        <srcpath> is a directory. Otherwise the file extension
                        of <srcpath> is replaced with ".o".
  -p[kg]=<pkgname>      Name to be used for package when exported globally
                        (i.e. when there's no package management.) If not
                        provided, <pkgname> is inferred from <srcpath>.
  -O                    Produce optimized output. See -help for details.
  -g                    Produce debuggable output. See -help for details.
  -i[ncr], -w[atch]     Incremental compilation (watches source for changes).
  -compress=<bool>      Explicitly enable or disable compression of generated
                        code. Defaults to "true" if -O is provided, otherwise
                        defaults to "false".
  -ts-disable           Do not attempt to interpret the package as a
                        TypeScript project.
  -ts-options=<json>    Apply <json> to TypeScript "compilerOptions" object on
                        top of options from tsconfig file.
  -map-root=<dir>       Source map "sourceRoot" value. Inferred from <srcpath>
                        and <outfile> by default.
  -no-maps              Do not read nor write any source maps.
  -no-incr-cache        Disable caching for incremental builds.
  -v[erbose]            Print details to stdout.
  -debug                Print lots of details to stdout. Implies -v.
  -dry                  Just print the configuration and exit.
`], desc2 = [`
<srcpath>
  Either a single javascript file or the path to a directory containing
  package source. If omitted, the current working directory is used.

<outfile>
  A filename prefix that is joined by type suffix for each output file
  produced. For a TypeScript project with declaration files, -o=a/b would
  create the following files:
    a/b.js       Code
    a/b.js.map   Source map
    a/b.d.ts     Type declarations

-g
  When provided:
  • Compression is disabled by default (pass -compress=true to explicitly
    enable).
  • All instances of \`const DEBUG = <constlit>\` are changed to replace
    \`<constlit>\` with \`true\`. This can be used to gate debugging code.

-O
  When provided:
  • Enables optimizations (dead-code elimination, constant folding, etc.)
  • Enables compression (pass -compress=false to explicitly disable.)
  • Unless -g is provided, all instances of \`const DEBUG = <constlit>\` are
    changed to replace \`<constlit>\` with \`false\`. This can be used to have
    debugging code stripped from the generated code, since constant folding
    together with dead-code elimination should remove code gated on "DEBUG".

  When neither -g or -O is provided, the goal of tspkg is to generate output
  as quickly as possible.

  Example of DEBUG elimination; in.js:

    const DEBUG = 0
    const assert = DEBUG ? require('assert') : function(){}
    export function bob(x) {
      assert(x > 0)
      return 4 / x
    }

  ${progname} -g in.js  # => out.js:

    const DEBUG = 1
    const assert = DEBUG ? require('assert') : function(){}
    exports.bob = function bob(x) {
      return 4 / x
    }

  ${progname} -O in.js  # => out.js:

    exports.bob=function(x){return 4/x};

  Note: Not providing -g or -O would yield code that's functionally identical
  to the in.js example above.
`];
  if (askedForHelp) {
    console.error(desc0.concat(desc1.concat(desc2)).join('\n'))
    process.exit(0)
  } else {
    console.error(desc1.join('\n') + `\nTry "${progpath} -help" for more information`)
    process.exit(1)
  }
}

function findTSConfig(srcpath) {
  let srcdir = srcpath
  let maxdepth = 3
  while (maxdepth--) {
    // FIXME: dirname('/') on windows
    let filename = Path.join(srcdir, 'tsconfig.json')
    if (isfile(filename)) {
      return filename
    }
    if (srcdir == '/') {
      break
    }
    srcdir = Path.dirname(srcdir)
  }
  return null
}

function inferPkgdir(cfg) {
  return cfg.tsconfigFile ? Path.dirname(cfg.tsconfigFile) :
         cfg.srcpathIsFile ? Path.dirname(cfg.srcpathabs) :
         cfg.srcpathabs
}

function inferPkgname(cfg) {
  return cfg.srcpathIsFile ? Path.basename(cfg.srcpathabs, Path.extname(cfg.srcpathabs)) :
         Path.basename(cfg.pkgdir)
}

function inferOutfile(cfg) {
  const tscfg = cfg.tsconfig && cfg.tsconfig.compilerOptions
  if (tscfg && tscfg.outFile) {
    return tscfg.outFile
  }

  const outdir =
    (tscfg && tscfg.outDir) ? tscfg.outDir :
    cfg.srcpathIsFile ? Path.dirname(cfg.srcpath) :
    cfg.srcpath

  return Path.join(outdir, (outdir == '..') ? (cfg.pkgname + '.out') : cfg.pkgname)
}

function array(v) {
  return v ? (Array.isArray(v) ? v : [v]) : []
}

const NotFound = Number.MAX_SAFE_INTEGER

function strfind(hay, needle) {
  let p = hay.indexOf(needle)
  return p == -1 ? NotFound : p
}

function parseLooseJSON(s) {
  return vm.runInNewContext('1 && ' + s)
}

function loadJSJSONFile(filename) {
  return filename ?
    parseLooseJSON(fs.readFileSync(filename, {encoding:'utf8'})) :
    null
}

function applyTSOptions(cfg, optionsJSON) {
  const options = parseLooseJSON(optionsJSON)
  if (cfg.tsconfig) {
    if (cfg.tsconfig.compilerOptions) {
      Object.assign(cfg.tsconfig.compilerOptions, options)
    } else {
      cfg.tsconfig.compilerOptions = options
    }
  } else {
    cfg.tsconfig = {compilerOptions: options}
  }
}

const cfg = {
  debug: false,
  optimize: false,
  compress: undefined,
  verbose: 0, // 1 = verbose, 2 = very verbose (-debug option)
  incremental: false,
  incrementalCache: true, // cache intermediates to speed up incremental builds
  
  srcpath: '.',   // aka pkgdir
  srcpathabs: '',
  srcpathIsFile: false, // true when file, false when dir or pattern
  srcdir: '', // inferred from srcpathabs or tsconfig
  pkgdir: '',  // = isfile(srcpathabs) ? dirname(srcpathabs) : srcpathabs
  srcfiles: [],
  srcfilesExclude: null, // string or string[] of glob patterns or paths to exlude
  outfile: '',
  outfileabs: '',
  outdir: '', // = dirname(outfileabs)
  pkgname: '',

  sourceMapsEnabled: true,
  sourceMapRoot: null,

  tsconfigFile: null, // non-null for TS projects
  tsconfig: null,
}

function main(argv, progpath) {
  const {opts, args} = parseargs(argv)
  // console.log({opts, args})
  opts.forEach((k, v) => {
    switch (k[0]) {
      case 'h': usage(progpath, true); break
      case 'o': cfg.outfile = checkArg(k, v, 'string', progpath); break
      case 'p': cfg.pkgname = checkArg(k, v, 'string', progpath); break
      case 'O': cfg.optimize = true; break
      case 'g': cfg.debug = true; break
      case 'i':
      case 'w': cfg.incremental = true; break
      case 'v': cfg.verbose = 1; break
      case 'd': {
        if (k == 'debug') { cfg.verbose = 2; break }
        if (k == 'dry') { break }
      }
      case 't': {
        if (k == 'ts-disable' || k == 'ts-options') { break }
      }
      default: {
        switch (k) {
          case 'compress':      cfg.compress = parseBool(v); break
          case 'no-maps':       cfg.sourceMapsEnabled = false; break;
          case 'no-incr-cache': cfg.incrementalCache = false; break;
          case 'map-root':      cfg.sourceMapRoot = v; break;

          case 'ts-disable':
          case 'ts-options':
          case 'dry':
            break
          
          default: {
            console.error(`Unexpected argument -${k}.`)
            usage(progpath)
          }
        }
      }
    }
  })

  if (cfg.compress === undefined) {
    // unless specified, enable compression when optimization is requested
    cfg.compress = cfg.optimize
  }

  // Parse options. Order matters.
  cfg.srcpath = args[0] || cfg.srcpath
  cfg.srcpathabs = Path.resolve(cfg.srcpath)
  cfg.srcpathIsFile = cfg.srcpathabs.indexOf('*') != -1 || isfile(cfg.srcpathabs)
  cfg.srcdir = cfg.srcpathIsFile ? Path.dirname(cfg.srcpathabs) : cfg.srcpathabs
  
  if (!opts['ts-disable'] &&
      (cfg.tsconfigFile = findTSConfig(cfg.srcpathabs)) &&
      (cfg.tsconfig = loadJSJSONFile(cfg.tsconfigFile)) )
  {
    let srcfiles = [] //, srcfileBasePaths = []
    if (cfg.tsconfig.include) {
      const globPatterns = array(cfg.tsconfig.include)
      srcfiles = srcfiles.concat(globPatterns)
      // srcfileBasePaths = srcfileBasePaths.concat(globPatterns.map(fn => {
      //   let p = Math.min(strfind(fn, '*'), strfind(fn, '{'), strfind(fn, '['))
      //   return (p != NotFound) ? fn.substr(0, p) : fn
      // }))
    }
    if (cfg.tsconfig.files) {
      const files = array(cfg.tsconfig.files)
      srcfiles = srcfiles.concat(files)
      //srcfileBasePaths = srcfileBasePaths.concat(files)
    }
    cfg.srcfiles = srcfiles
    cfg.srcfilesExclude = array(cfg.tsconfig.exclude) || null
    cfg.pkgdir = Path.dirname(cfg.tsconfigFile)

    if (cfg.tsconfig.compilerOptions) {
      const copt = cfg.tsconfig.compilerOptions
      if (copt.rootDir) {
        cfg.srcdir = Path.resolve(cfg.pkgdir, copt.rootDir)
      } else if (copt.rootDirs && Array.isArray(copt.rootDirs) && copt.rootDirs.length) {
        cfg.srcdir = Path.resolve(cfg.pkgdir, commonParentDir(copt.rootDirs))
      }
      // else srcdir = Path.join(cfg.pkgdir, commonParentDir(srcfileBasePaths))
    }
  } else {
    cfg.pkgdir = inferPkgdir(cfg)
    cfg.srcfiles = [ Path.join(cfg.pkgdir, '**/*.js') ]
  }

  if (!cfg.pkgname) { cfg.pkgname = inferPkgname(cfg) }

  // outdir must be relative to outfile in such a way that
  //   outdir + outfile = cfg.outfileabs
  //
  // Thus:
  //  1. Let outfile be the result of the value of the -o option
  //  2. If outfile is empty (no -o option or empty option):
  //     2.a. If srcpathabs is a file, let outfile be the result of joining the
  //          dirname of srcpath with pkgname and ".out".
  //     2.b. If srcpathabs is a directory or glob pattern, let outfile be the
  //          result of joining srcpath with pkgname
  //  3. Let outfileabs be the absolute path of outfile resolved from the
  //     current working directory
  //  4. Let outdir be the dirname of outfileabs
  //  5. Let outfile' be the basename of outfile
  //
  if (!cfg.outfile) { cfg.outfile = inferOutfile(cfg) }
  if (cfg.outfile.substr(-3) == '.js') {
    // strip ".js" suffix since we add it on depending on .d.ts, or .js/.js.map
    cfg.outfile = cfg.outfile.substr(0, cfg.outfile.length - 3)
  }
  cfg.outfileabs = Path.resolve(cfg.pkgdir, cfg.outfile)
  cfg.outfile = Path.basename(cfg.outfile)
  cfg.outdir = Path.dirname(cfg.outfileabs)

  if (opts['ts-options']) {
    applyTSOptions(cfg, opts['ts-options'])
  }

  if (opts.dry || cfg.verbose) {
    const keys = Object.keys(cfg)
    const klen = keys.reduce((z, k) => Math.max(z, k.length), 0)
    const sp = '                           '
    console.log(
      keys
        .filter(k => (cfg.verbose > 1) || !({tsconfig:1})[k] )
        .map(k => k + ': ' + sp.substr(0, klen - k.length) + repr(cfg[k]))
        .join('\n')
    )
    if (opts.dry) {
      process.exit(0)
    }
  }

  // proper working directory required by typescript to resolve types and modules
  process.chdir(cfg.pkgdir)

  const C = gutil.colors

  gulp.on('start', e => { // gulp3 calls this task_start
    // if (!cfg.verbose || ({default:1})[e.name]) { return }
    console.log(gutil.colors.blue.bold(e.name))
  });

  gulp.on('stop', e => { // gulp3 calls this task_stop
    console.log(`${C.green.bold(e.name)} done ${C.grey('('+fmthrtime(e.duration)+')')}`)
  })

  gulp.on('error', e => { // gulp3 calls this task_err
    const err = e.error
    let msg = C.red.bold(e.name + ' failed')
    if (err.name) {
      msg += ' with ' + err.name
    }
    if (e.duration) {
      msg += ' after ' + fmthrtime(e.duration)
    }
    if (err.plugin) {
      msg += ' in ' + err.plugin
    }
    msg += ':\n'
    if (err.showStack && err.stack) {
      msg += err.stack
    } else if (err.fileName) {
      let errmsg = err.message
      if (errmsg.indexOf(err.fileName + ':') == 0) {
        errmsg = errmsg.substr(err.fileName.length + 1).trim()
      }

      msg += C.cyan.bold(
        err.fileName.substr(0, cfg.pkgdir.length) == cfg.pkgdir ?
          Path.relative(cfg.pkgdir, err.fileName) : err.fileName
      ) + ': ' + errmsg
    } else {
      msg += err.toString()
    }
    console.error(msg)
    if (cfg.verbose > 1 && e.error.stack) {
      console.error(e.error.stack.substr(e.error.stack.indexOf('\n')+1))
    }
    if (!cfg.incremental) {
      process.exit(1)
    }
  })

  // gulp v>=4
  gulp.parallel(['compile'])(function(err) {
    if (err) {
      if (!cfg.incremental) {
        process.exit(1)
      }
    } else if (cfg.incremental) {
      console.log('watching files for changes')
      gulp.watch(cfg.srcfiles, compile);
    }
  });
  // gulp v<=3
  // gulp.start.apply(gulp, [cfg.incremental ? 'watch' : 'compile']);

  function formatError(e) {
    if (!e.err) { return e.message; }
    // PluginError
    if (typeof e.err.showStack === 'boolean') {
      return e.err.toString();
    }
    // Normal error
    if (e.err.stack) {
      return e.err.stack;
    }
    // Unknown (string, number, etc.)
    return new Error(String(e.err)).stack;
  }
}


function makeTSCompilerOptions(cfg) {
  // These settings are used for compilerOptions in the absence of cfg.tsconfig.compilerOptions
  // options which might be replaced by tsconfig
  const defaultOptions = {
    pretty: true,
    alwaysStrict: true,
    forceConsistentCasingInFileNames: true,
    moduleResolution: "node",
    diagnostics: cfg.debug,
    // declaration: true,
    // noImplicitAny: false,
    // experimentalDecorators: true,
    // emitDecoratorMetadata: true,
  }

  // options which replace those of tsconfig
  let options = {
    module: "es2015", // 'commonjs', 'amd', 'system', 'umd' or 'es2015'
    target: "ESNEXT", // results to through babel
    lib: [ "es6", "dom" ],
    noEmitOnError: true,
    outDir: cfg.outdir,
    baseUrl: cfg.pkgdir,
    rootDir: cfg.srcdir,
    //rootDirs: [cfg.pkgdir],
  }

  // Options unsupported by gulp-typescript:
  // - sourceMap, inlineSourceMap, inlineSources, sourceRoot (managed by gulp-sourcemaps)
  // - watch
  // - project
  // - help, version

  options = Object.assign(
    (cfg.tsconfig && cfg.tsconfig.compilerOptions ?
      Object.assign({}, defaultOptions, cfg.tsconfig.compilerOptions) :
      Object.assign({}, defaultOptions)),
    options)

  if (cfg.compress) {
    options.removeComments = true
  }
  if (options.outFile) {
    delete options.outFile
  }
  return options
}

const BABEL_STAGE_1 = 1  // process individual files
const BABEL_STAGE_2 = 2  // process final package file
let babelConfig = new Map; // state => config

function getBabelConfig(cfg, stage) {
  let C = babelConfig.get(stage)
  if (C) {
    return C
  }

  const builtin = 'tspkg:'

  C = {
    plugins: [],
    compact:    cfg.compress,
    minified:   cfg.compress,
    comments:   !cfg.compress,
    sourceRoot: cfg.pkgdir,
  }

  if (stage == BABEL_STAGE_1 && (cfg.debug || cfg.optimize)) {
    // prep plugin runs for both debug and optimize
    C.plugins = C.plugins.concat([
      [builtin + "prep", {
        "consts": new Map([
          ["DEBUG", {type:"BooleanLiteral", value: cfg.debug}],
        ]),
      }],
    ])
  }

  const pkgPlugin = [builtin + "pkg", {strict: true, tspkgConfig: cfg}]
  const dcePlugin = [builtin + "dce", {tspkgConfig: cfg}]
  const minifyPlugin = [builtin + "minify", {tspkgConfig: cfg}]

  if (cfg.optimize) {
    // plugins enabled when asked to optimize output

    if (stage == BABEL_STAGE_1) {
      C.plugins = C.plugins.concat([
        dcePlugin,
        minifyPlugin,
        "minify-constant-folding",
        pkgPlugin,
        "minify-flip-comparisons",
        "minify-guarded-expressions",
        "minify-infinity",
        cfg.compress && "minify-numeric-literals",
        cfg.compress && "transform-simplify-comparison-operators", // x===3 -> x==3 if x is num
        cfg.compress && "transform-minify-booleans", // true => !0, false => !1
        cfg.compress && "transform-property-literals", // {"bob":1} -> {bob:1}
        "minify-type-constructors", // Number(5) -> +5, Array(4) -> [,,,]
        // "transform-member-expression-literals", // only needed when targeting <ES5
        // "minify-simplify", // `if (x) { a() }` -> `x && a();`
        "transform-regexp-constructors", // new RegExp(foo+'c', 'i') -> /ab+c/i
        // "transform-undefined-to-void", // undefined -> void 0
      ])
    } else if (stage == BABEL_STAGE_2) {
      // stage 2 is run over the concatenated product, meaning we can't cache
      // the result and the amount of code is significant, so let's stick to
      // only plugins which do something truly valuable.
      C.plugins = C.plugins.concat([
        dcePlugin,
        "minify-constant-folding",
        "transform-merge-sibling-variables",
        cfg.compress && "minify-mangle-names",
        "minify-simplify",
      ])
    }

  } else {
    // plugins enabled when NOT asked to optimize output
    if (stage == BABEL_STAGE_1) {
      C.plugins = C.plugins.concat([
        pkgPlugin,
      ])
    }
  }

  // remove falsy entries
  C.plugins = C.plugins.filter(p => p)

  if (cfg.verbose > 1) {
    // we print before converting plugin paths
    console.log('effective babel configuration for stage '+stage+':\n', repr(C))
  }

  // Babel plugins have complicated resolution rules.
  // Rewrite plugins to use absolute paths to get around it.
  const updatePlugin = (path, config) => {
    if (path.indexOf(builtin) == 0) {
      return __dirname + "/lib/babel-plugin-" + path.substr(builtin.length)
    } else if (path[0] !== '/') {
      return __dirname + '/node_modules/babel-plugin-' + path
    }
    return path
  }
  C.plugins.forEach((plugin, i) => {
    if (Array.isArray(plugin)) {
      plugin[0] = updatePlugin(plugin[0], plugin[1])
    } else {
      C.plugins[i] = updatePlugin(plugin)
    }
  })

  babelConfig.set(stage, C)
  return C
}


let tsProject = null // lazily-initialized by task "tsc"

function getTSProject(cfg) {
  if (!tsProject) {
    const ts = require('gulp-typescript');
    tsProject = ts.createProject(makeTSCompilerOptions(cfg));
    tsProject.projectDirectory = cfg.pkgdir
    if (cfg.verbose > 1) {
      // console.log('typescript:\n', repr(tsProject))
      console.log('effective typescript configuration:\n', repr(tsProject.options))
    }
  }
  return tsProject
}


const through = require('through2')
let applySourceMap //lazy-loaded
//
// interface FileContent {
//   contents   :Buffer
//   sourceMap? :SourceMap
// }
// interface File extends FileContent {
//   path     :string
//   relative :string
// }
// transformer :(file :File, encoding :string)=>FileContent|null
//
//   If `file` has file.sourceMap, then the transformer should return a new
//   source map that is the mapping from file.contents to result.contents.
//
//   If transformer returns null, no transformation is applied.
//
function transform(transformer) {
  return through.obj(function(file, encoding, callback) {
    const result = transformer(file, encoding);
    if (result) {
      file.contents = result.contents
      if (file.sourceMap) {
        // apply source map to the chain
        if (!result.sourceMap) {
          throw new Error('transformer did not produce a source map')
        }
        if (!applySourceMap) {
          applySourceMap = require('vinyl-sourcemaps-apply')
        }
        applySourceMap(file, result.sourceMap);
      }
    }
    this.push(file);
    callback();
  })
}


function dtsModulize() {
  return transform((file, encoding) => {
    const filename = file.relative || Path.basename(file.path);
    assert(!file.sourceMap) // d.ts files are expected not to have source maps

    if (file.contents.length == 0) {
      return null
    }
    
    assert.equal(filename.substr(-5), '.d.ts')
    const moduleName = filename.substr(0, file.relative.length-5)

    const indent = '  '
    const header = "declare module '" + moduleName.replace(/'/g, "\\'") + "' {\n" + indent
    const trailer = '}\n'
    let body = file.contents.toString(encoding).trim()

    if (body.length > 0) {
      body = header +
      (body
        .replace(/declare /g, '') //<- FIXME proper parser
        .replace(/(\r?\n)(\s{4})/mg, '$1' + indent)
        .replace(/(\r?\n)/gm, '$1' + indent)
        .replace(/import\s+(.+\s+|)'\.\//g, "import $1'")
          // ^ FIXME something that's not horrible
      )
      + '\n' + trailer
    }

    return {
      contents: new Buffer(body, encoding)
    }
  })
}


function compile() {
  const useIncrCache = cfg.incremental && cfg.incrementalCache

  // Load these as late as possible since they are HUGE and SLOW.
  // On a maxed-out MacBook Pro 15" i7, these few requires takes about 350ms  :.(..
  const babel      = require('./lib/gulp-babel.js')
  const sourcemaps = require('gulp-sourcemaps')
  const merge      = require('merge2')
  const concat     = require('./lib/gulp-concat.js')
  const gulpPkg    = require('./lib/gulp-pkg.js')
  const gcached    = useIncrCache && require('gulp-cached')
  const gremember  = useIncrCache && require('gulp-remember')

  const sourceMapRoot = cfg.sourceMapRoot || Path.relative(cfg.outdir, cfg.pkgdir)

  // TODO
  //  so when we build wasm-util it's tsconfig has include=["src/**/*.ts"] and so
  //  cfg.pkgdir does not include "/src", which means that relname of files instead
  //  includes "src". Whiiich in turn leads to module identifiers including "src".
  //  babel-plugin-pkg infers module id from source.value when encountering an
  //  import (e.g. `import "./foo/bar"` is interpreted as module id "foo/bar").
  //  The module id inferred by babel-plugin-pkg must match those inferred by
  //  gulp-pkg, or dependency resolution will break.
  //
  //  Idea: use glob or whatever to expand input files before passing them to gulp.
  //  Then use commonParentDir to derive a better cfg.pkgdir which should do it.
  //

  const sourceFiles = new Map
  cfg.sourceFiles = sourceFiles

  const tsProject = getTSProject(cfg)

  let srcfiles = cfg.srcfiles
  if (cfg.srcfilesExclude && cfg.srcfilesExclude.length) {
    // vinyl-fs used by gulp wants excludes at end of source glob patterns.
    // see https://github.com/gulpjs/vinyl-fs#srcglobs-options
    for (const pattern of cfg.srcfilesExclude) {
      srcfiles.push('!' + pattern)
    }
  }

  let source = gulp.src(srcfiles, {
    cwd:    cfg.pkgdir,
    ignore: cfg.srcfilesExclude,
  }).pipe(through.obj((file, encoding, callback) => {
    // Fix file base
    file.base = cfg.srcdir
    if (cfg.verbose > 1) {
      console.log('[src]', JSON.stringify(file.base) + ', ' + JSON.stringify(file.relative))
    }
    // Register source file
    sourceFiles.set(file.relative, file)
    callback(null, file)
  }))

  if (cfg.sourceMapsEnabled) {
    source = source.pipe(sourcemaps.init({
      identityMap: false, //cfg.debug,
        // Set to true to generate a full valid source map encoding no changes
        // (slower, only for Javascript and CSS) instead of the default empty
        // source map (no mappings, fast). Use this option if you get missing
        // or incorrect mappings, e.g. when debugging.
      }
    ))
  }

  if (useIncrCache) {
    source = source.pipe(gcached('src'))
  }

  let tsResult = source.pipe(tsProject())
    .on('error', function (error) {
      if (!cfg.incremental) {
        throw error
      }
    })

  let dtsPipe = tsProject.options.declaration && tsResult.dts.pipe(dtsModulize())
  if (dtsPipe) {
    if (useIncrCache) {
      dtsPipe = dtsPipe.pipe(gremember('dts'))
    }
    dtsPipe = dtsPipe.pipe(concat(cfg.outfile + '.d.ts', {separator: ''}))
  }

  let jsPipe = tsResult.js
    .pipe(through.obj((file, encoding, callback) => {
      // Fix path of source inf sourcemap. TSC converts the path to be relative from outdir
      // but we need it to be relative to srcdir for correlation purposes.
      if (file.sourceMap && file.sourceMap.sources && file.sourceMap.sources.length) {
        file.sourceMap.sources[0] = Path.relative(
          cfg.srcdir,
          Path.join(cfg.outdir, file.sourceMap.sources[0])
        )
      }
      // console.log(`[tspkg] (after ts) ` +
      //   `file.sourceMap.sources[0]="${file.sourceMap.sources[0]}" ` +
      //   `file.base="${file.base}" ` +
      //   `file.relative="${file.relative}" ` +
      //   `file.path="${file.path}"`
      // )
      callback(null, file)
    }))
    .pipe(babel(cfg, getBabelConfig(cfg, BABEL_STAGE_1)))


  if (useIncrCache) {
    jsPipe = jsPipe.pipe(gremember('js'))
  }

  jsPipe = jsPipe
    .pipe(gulpPkg(cfg))
    .on('error', function (error) {
      console.error(error.tspkgCode ?
        (error.styledMessage || error.message) :
        (error.stack || String(error))
      )
      if (!cfg.incremental) {
        process.exit(1)
      }
    })

  if (cfg.optimize) {
    jsPipe = jsPipe.pipe(babel(cfg, getBabelConfig(cfg, BABEL_STAGE_2)))
  }

  if (cfg.sourceMapsEnabled) {
    jsPipe = jsPipe.pipe(sourcemaps.write('.', {
      addComment: true,
        // true: a comment containing or referencing the source map is added.
        // false: no comment added (for "secret" source maps)
      includeContent: false,
        // true to embed copy of all source code
      sourceRoot: sourceMapRoot,

      // relative source names that are rooted in sourceRoot
      mapSources: sourcePath => {
        return Path.relative(cfg.pkgdir,
          Path.isAbsolute(sourcePath) ? sourcePath : Path.join(cfg.outdir, sourcePath))
      },

      // See https://github.com/floridoo/gulp-sourcemaps#write-options for more
    }))
  }

  const outPipe = dtsPipe ? 
    merge([ dtsPipe, jsPipe ]) :
    jsPipe

  // Note: Gulp uses vinyl-fs which in turn does this concatenation of
  // outdir + relative filename.
  return outPipe.pipe(gulp.dest(cfg.outdir, { cwd: cfg.outdir }))
}

gulp.task('compile', compile)

// needed by gulp3
// gulp.task('watch', ['compile'], () => {
//   gulp.watch(cfg.srcfiles, ['compile']);
// })

if (module.id == '.') {
  main(process.argv.slice(2), process.env._ || basename(process.argv[1]))
}
